name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
